@startuml Architecture
    title Architecture

WinFormsApp --> Controllers
WinFormsApp --> ViewModels
WinFormsApp --> Types
WinFormsApp --> Utils

Controllers --> ViewModels
Controllers --> Models
Controllers --> Types
Controllers --> Utils

ViewModels --> Models
ViewModels --> Utils

Models --> Types
Models --> Utils

class WinFormsApp{
}

class ViewModels{
}

class Controllers{
}

class Types{
}

class Utils{
}

class Models{
}

@enduml