@startuml UseCases
    left to right direction
    title Use Cases

actor User

usecase "Add Task" as UC101
usecase "Update Task" as UC102
usecase "Delete Task" as UC103
usecase "Display Task By Priority And DueDate" as UC104

usecase "Push Task Action History" as UC201
usecase "Undo" as UC202
usecase "Redo" as UC203
usecase "Display Task Action History" as UC204
usecase "Display Task Action Redos" as UC205

usecase "Mark Task Urgent" as UC301
usecase "Mark Task Normal" as UC302
usecase "Display Urgent Tasks" as UC303
usecase "Process Task" as UC304

usecase "Display Task In Category Tree" as UC501

User --> UC101
    UC101 ..> UC104 : <<include>>
    UC101 ..> UC201 : <<include>>
User --> UC102
    UC102 ..> UC104 : <<include>>
    UC102 ..> UC201 : <<include>>
User --> UC103
    UC103 ..> UC104 : <<include>>
    UC103 ..> UC201 : <<include>>
    
    UC201 ..> UC204 : <<include>>

User --> UC202
    UC202 ..> UC104 : <<include>>
    UC202 ..> UC204 : <<include>>
    UC202 ..> UC205 : <<include>>
User --> UC203
    UC203 ..> UC104 : <<include>>
    UC203 ..> UC204 : <<include>>
    UC203 ..> UC205 : <<include>>

User --> UC301
    UC301 ..> UC303 : <<include>>
    UC301 ..> UC501 : <<include>>
User --> UC302
    UC302 ..> UC303 : <<include>>
    UC302 ..> UC501 : <<include>>
User --> UC304
    UC304 ..> UC303 : <<include>>
    
User --> UC501
@enduml