@startuml Architecture
    skin rose
    title Architecture

WinFormsApp --> Controllers
WinFormsApp --> ViewModels
WinFormsApp --> Types

Controllers --> ViewModels
Controllers --> Models
Controllers --> Types

ViewModels --> Models

Models --> Types

package WinFormsApp{
}

package ViewModels{
}

package Controllers{
}

package Types{
}

package Models{
}

@enduml