@startuml Architecture
    title Architecture

WinFormsApp --> Controllers
WinFormsApp --> ViewModels
WinFormsApp --> Types

Controllers --> ViewModels
Controllers --> Models
Controllers --> Types

ViewModels --> Models

Models --> Types

class WinFormsApp{
}

class ViewModels{
}

class Controllers{
}

class Types{
}

class Models{
}

@enduml